services:
  web:
    container_name: frontend-real-estate
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    # restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_KEY=${NEXT_PUBLIC_API_KEY}
      - NEXT_PUBLIC_AUTH_DOMAIN=${NEXT_PUBLIC_AUTH_DOMAIN}
      - NEXT_PUBLIC_PROJECT_ID=${NEXT_PUBLIC_PROJECT_ID}
      - NEXT_PUBLIC_STORAGE_BUCKET=${NEXT_PUBLIC_STORAGE_BUCKET}
      - NEXT_PUBLIC_MESSAGING_SENDER_ID=${NEXT_PUBLIC_MESSAGING_SENDER_ID}
      - NEXT_PUBLIC_APP_ID=${NEXT_PUBLIC_APP_ID}
      # - CHOKIDAR_USEPOLLING=true
      # if CPU is high, uncomment the following snippet.
      # you can also increase the number to reduce the CPU aggressive usage.
      # - CHOKIDAR_INTERVAL=1000
      # - WATCHPACK_POLLING=true
    # insure container uses its own node_modules for consistency
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - bridge_network

networks:
  bridge_network:
    name: real_estate_network
    external: true
